[package]
name = "starpls_ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
glob = "0.3.1"
thiserror = "1.0.56"
starpls_bazel = { path = "../starpls_bazel" }

[dev-dependencies]
tempfile = "3.0"